name: Cron Heartbeat

on:
  schedule:
    - cron: '31 17 * * *'

  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Heartbeat
        run: |
          echo "SCHEDULE FUNCIONOU"
          echo "UTC:"
          date -u
